# Generated by Django 2.2.2 on 2019-06-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190613_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_date',
            new_name='date_of_death',
        ),
    ]
